# Publishes the project to GitHub Releases, CurseForge, and Modrinth
name: Publish Project

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # any SemVer tag, e.g. v1.2.3

concurrency:
  group: publish-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to create GitHub releases

    env:
      DISABLE_BUILDSCRIPT_UPDATE_CHECK: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Build
        uses: ./.github/actions/build_setup

      - name: Build Project
        run: ./gradlew reobfjar --warning-mode all --build-cache

      - name: Publish to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: "build/libs/*.jar"
          generate_release_notes: true
          fail_on_unmatched_files: true
